Draft demo project to show how Microsoft Ribbon Framework (COM) can be used with a Eiffel Vision2 Window
Note:

1.You must first install Microsoft Windows SDK 7.0.

    1)Otherwise, when C compile you would get errors like:

    c:\program files (x86)\microsoft sdks\windows\v7.0a\include\ocidl.h(3637) : error C2143: syntax error : missing ')' before '('
    c:\program files (x86)\microsoft sdks\windows\v7.0a\include\ocidl.h(3637) : error C2081: '__RPC__in_range' : name in formal parameter list illegal

    2)Only Windows SDK 7.0 has uicc.exe which is used for compile Ribbon markup xml file. The uicc.exe doesn't come with both Visual Studio 2008 and Visual Studio 2010. In the project, the ribbon.bml, ribbon.h and eiffelribbon.rc are compiled/generated by uicc.exe. They are needed when you linking this Eiffel project. Otherwise, the RC.EXE would report missing files.

2.The C part of this project are mostly borrowed from the project attached in following page:
http://www.codeproject.com/KB/toolbars/Ribbon.aspx

3.For the key feature to attached ribbon to Vision2 window please check {MAIN_WINDOW}.`user_initialization'

SVN: 84895@trunk